export function mapJobToRow(job: Record<string, unknown>, organizationId: string, index: number) {
  return {
    organization_id: organizationId,
    external_id: String(job.id || job.url || `${index}-${Math.random()}`),
    title: job.title || "Untitled",
    organization_name: job.organization || null,
    organization_url: job.organization_url || null,
    organization_logo: job.organization_logo || null,
    url: job.url || null,
    locations_derived: job.locations_derived || null,
    country:
      (job.countries_derived as Array<{ country?: string }>)?.[0]?.country || null,
    city:
      (job.cities_derived as Array<{ city?: string }>)?.[0]?.city || null,
    description_text: job.description_text || null,
    source: job.source || null,
    source_type: job.source_type || null,
    employment_type: job.employment_type || null,
    work_arrangement: job.ai_work_arrangement || null,
    ai_taxonomies: job.ai_taxonomies_a || null,
    ai_key_skills: job.ai_key_skills || null,
    ai_salary_currency: job.ai_salary_currency || null,
    ai_salary_min: job.ai_salary_minvalue || null,
    ai_salary_max: job.ai_salary_maxvalue || null,
    ai_salary_unit: job.ai_salary_unit || null,
    date_posted: job.date_posted || null,
    // AI fields
    ai_experience_level: job.ai_experience_level || null,
    ai_employment_type: job.ai_employment_type || null,
    ai_benefits: job.ai_benefits || null,
    ai_core_responsibilities: job.ai_core_responsibilities || null,
    ai_requirements_summary: job.ai_requirements_summary || null,
    ai_education_requirements: job.ai_education_requirements || null,
    ai_keywords: job.ai_keywords || null,
    ai_visa_sponsorship: typeof job.ai_visa_sponsorship === "boolean" ? job.ai_visa_sponsorship : null,
    ai_hiring_manager_name: job.ai_hiring_manager_name || null,
    ai_hiring_manager_email: job.ai_hiring_manager_email_address || null,
    ai_working_hours: typeof job.ai_working_hours === "number" ? job.ai_working_hours : null,
    // Derived fields
    domain_derived: job.domain_derived || null,
    remote_derived: typeof job.remote_derived === "boolean" ? job.remote_derived : null,
    // LinkedIn fields
    linkedin_org_industry: job.linkedin_org_industry || null,
    linkedin_org_employees: typeof job.linkedin_org_employees === "number" ? job.linkedin_org_employees : null,
    linkedin_org_url: job.linkedin_org_url || null,
    linkedin_org_type: job.linkedin_org_type || null,
    linkedin_org_headquarters: job.linkedin_org_headquarters || null,
    linkedin_org_description: job.linkedin_org_description || null,
    linkedin_org_specialties: job.linkedin_org_specialties || null,
    linkedin_org_founded_date: job.linkedin_org_foundeddate || null,
    linkedin_org_slug: job.linkedin_org_slug || null,
    linkedin_org_followers: typeof job.linkedin_org_followers === "number" ? job.linkedin_org_followers : null,
    linkedin_org_size: job.linkedin_org_size || null,
    linkedin_org_recruitment_agency: typeof job.linkedin_org_recruitment_agency_derived === "boolean" ? job.linkedin_org_recruitment_agency_derived : null,
    raw_data: job,
  };
}
